apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-service
  namespace: argocd
spec:
  project: default
  syncPolicy:
   automated: {}
  source:
    repoURL: https://github.com/Mathew1988/argo-kustomize
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc